package com.gpfreetech.scratchview.demo;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Environment;
import android.view.View;

import androidx.core.app.ShareCompat;
import androidx.core.content.FileProvider;

import java.io.File;
import java.io.FileOutputStream;

public class Util {
    public static String[] arr_month = {"JAN", "FEB", "MAR", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPT", "OCT",
            "NOV", "DEC"};
    public static String[] arr_thought = {"A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
            "Life just is. You have to flow with it. Give yourself to the moment.Let it happen.",
            "Pure logic is the ruin of the spirit.",
            "There is an Indian belief that everyone is a house of four rooms: a physical, a mental, an emotional and a spiritual room. Most of us tend to live in one room most of the time, but  unless we go into every room every day, even if only to keep it aired, we are not complete",
            "Self-importance is our greatest enemy. Think about it-- what weakens us is feeling offended by the deeds and misdeeds of our fellowmen. Our self-importance requires that we spend most of our lives offended by someone.",
            "I have great faith in fools-- self-confidence my friends call it.",
            "We can't do great things in this life . . . We can only do small things with great love.",
            "If you want to change somebody, don�t preach to him. Set an example and shut up.",
            "I don�t really go through a process, it goes through me.",
            "The chains of habit are generally too small to be felt until they are too strong to be broken.",
            "How dreadful knowledge of the truth can be when there�s no help in the truth.",
            "A drop of water in lake, there is no identity, But if it is on leaf of lotus, it shines like pearl,Be in d best place where U can shine.",
            "Its better to look ahead and prepare than to look back and despair....!",
            "Simplicity is the ultimate sophistication.",
            "golden words of success see the clock only when you dnt have work, dont see clock when u r working.,clock is a lock for success.",
            " The past is to prove that no one is perfect and the future is to prove that everyone can change..!",
            "Be simple but look stylish Be tough but look soft Be tense but look cool Be a beginner but look winner.",
            "If you cant forget some things in life, make sure you dont give yourself time to remember them...!!",
            "The man who learns the art of sharing is the richest man in the world. He may be poor, but his inner being is rich...!",
            "Live like there is no tomorrow! Constantly move forward and appreciate the motivation for your existence! It has cause! It has meaning! It has reason! Never give up and never look back! Choose to make a meaningful difference in your life and the life of others. Do it every day and DO IT BIG!!!",
            "Life is a notebook , 2 pages are already written by god .......1st page is birth .Last page is death .Centre pages are empty .Fill them with smile , love & sacrifice but not with ego and false attitude",
            "Never blame a day in ur life. Good day gives u happiness and bad day gives u experience. Both are essential in life! All are god blessing!",
            "Do something each day To bring you A little closer To yours dreams.",
            "No matter how small the step or how long the journey, a little every day will get you there.",
            "Each morning we are born again. What we do today is what matters most",
            "You don�t need business degrees or vast experience to begin a business:you need a great idea",
            "If you want to change who you are, begin by changing the size of your dream. Even if you are broke, it does not cost you anything to dream of being rich. Many poor people are poor because they have given up on dreaming",
            "Before you assume, learn the facts Before you judge, understand why Before you hurt someone,feel Before you speak, think",
            "Luck is what happens when preparation meets opportunity.",
            "Lovely chocolate and Lovely you And Lovely are the things you do, But the loveliest is the friendship of the two, One is Me and Other is You !",
            "Even a big pot full of water will b emptied By a small hole, In the same way, A little anger or ego will burn up The nobility of GOOD HEART..",
            "If v can laugh wen v r completely broken up, Den der can b nothing dat can break usnext time..",
            "In d chase between cat & mouse, mostly d mouse wins, bcoz d cat is running 4 its food, but d mouse 4 its life. PURPOSE IS MORE IMPORTANT.DEN NEED",
            "All misery & pain cums from ATTACHMENT!!!",
            "Help all who r trying to b good And to do good.....",
            "The best thing to give ur enemy is FORGIVENESS",
            "Wen human mind is silent,Den DIVINE MIND is inActive Expression.",
            "Many 'HEARTS' r opened by 'PLEASE' Den by keys",
            "Success lies not in FLYING, But in TRYING..",
            "Hope for d best, But b prepared for d worst.",
            "Living in the favourable & unfavourable situation is called- PART OF LIFE, But smiling in all those situation is called- ART OF LIFE....",
            "Believe in the principle of KARMA NOT IN RAASHI Remember RAM&RAVAN KRISHNA&KANS GANDHI&GODSE had same RAASHI But their KARMAM made them Different....",
            "1.	Everything in life has a beautiful ending-if its nOt beautiful-then its nOt d endits just the beginning of sOmething mOre Beautiful.......!",
            "GOD Is A Sure Paymaster, He May Not Pay At The End Of Every Week Or Month Or Year, But Remember He Pays In The End. So Keep Faith In GOD....",
            "There is no royal road to success. BUT after success,every road becomes royal. Best wishes for those who believe in struggle.....",
            "A baby fish asked her mother:Y can't v live on Earth? other fish: Earth is not the place 4 fishes. Earth is made 4 selfishes",
            "GOD Ven I Lose Hope Help Me 2 Remember Dat Ur Luv Is Greater Dan My Disappointmnts & Ur Plans 4 My Life R Better Dan My Dreams....!",
            ".Life is more strict than a Teacher. A Teacher Teaches Lesson & Then keeps The Exam. But Life Keeps The Exam First & Then Teaches The LESSON.",
            "Shakespear said: 'I always feel happy' You know why? Because I dont expect anything from anyone!!!. Expectations always hurt.",
            "U r doing,what U want But Ur getting,what want Instead U do,what I want. U will get,what U want",
            "There�s never a wrong time to do ryt thing",
            "Man Wishes to fly like a cuckoo Dance like a peacock Swim like a fish But Man ds'nt wish to live like a MAN",
            "Funny but true In The Past,Nobody had Watch But Everyone had Time. Now everyone has a Watch but NOBODY has TIME.",
            "Why do we have so many Temples, if God is everywhere? A wise man said:Air is everywhere, but we still need a fan to feel it....",
            "expanded meaning of PAINS is.. P_ositive A_pproach I_n N_egative S_ituation We can Bear any Pain.",
            "All of us Do Not Have Equal Talent. But All of us Have an Equal Opportunity to Develop our Talents...",
            "TIME & LIFE are the co-teachers LIFE teaches us the use of TIME...... And TIME teaches us the value of LIFE.....!",
            "Silence of a Genius is More Disastrous than Weapons Patience of a Good Person is more Powerful than Anger of thousand Silly Persons",
            "1tree makes 1 lakh Matchstick can burn 1lakh trees... similriy 1 negtive Thought or Doubt can burn thousands of Dreams.. SO BE POSTIVE..",
            "Read D below phrase carefully 2 know D fact of life. God has given us 'REAL EYES' to 'REALISE' the 'REAL LIES'",
            "Strong people commit mistakes as weak people. Only difference is Stronger people admit mistakes, But Weaker one will look for excuses.",
            "here is a slogan written in the entrance gate of all schools in JAPAN �IF U CANNOT DO, NO OTHER HUMAN IN THE WORLD CAN DO IT�.belive in urself.",
            "Life Gives answers in3ways: 1-It says yes & givesYou what you want 2-It says no & givesYou something better 3-It says wait&givesYou the best",
            "Respect the OLD when ur YOUNG Help the WEAK when ur STRONG Confess the FAULT when ur WRONG bcoz oneday in life u will be OLD,WEAK& WRONG.",
            ".Luck is not in our hands. But work is in our hands. Our work can make our luck, But Luck cant make our work. So trust yourself than luck.",
            "THINK before U Speak T-Is it TRUE ? H-Will it HELP ? I-Is it INSPIRING ? K-Is it KIND?",
            "Evry1 wants happiness, no 1 needs pain bt its nt possible 2 get a rainbow without a little rain! So faceLIFE with confidence",
            ".Life is an Echo, All cums Back, D Gud,d Bad,d False,d True: So Give d World d Best u Hv & d Best wil Come Back 2 U.",
            "Good Relations Are Like Trees They Demand Attention & Care In the Begining But Once They Blossom They Provide Shade In All Situations Of LIFE.",
            ".Life is all about three things. Winning, Losing and Sharing. Winning- others hearts, Losing- negativity and Sharing- Happy moments",
            "Easy To Loose someone by saying Life. Difficult to get back that Porson by saying True. its a fact in Everybody's Life.",
            "Positive Thinking May Not Guarantee Success, Bt Negative Thinking DEFiNiTELY Guarantees Failure! So always hv +ve attitude.",
            "You Are A Precious Diamond In GODs Hands When GOD Sharpens Your Edges, Its Really Painful But That Will Make You More Shiny & Precious.",
            "Relationship is like a book, it takes few seconds to burn but years to write. So write it carefully n never let it burn.",
            "Winners always compares their achievements with their own goals,",
            " When you rise in the morning, give thanks for the light, for your life, for your strength. Give thanks for your food and for the joy of living. If you see no reason to give thanks, the fault lies within yourself.",
            " There is no limit to the good you can do if you have courage, conviction, and a caring heart.",
            " The struggle begins in the mind. Defeat it in your mind and you will wipe it out of your heart. The heart is the birthplace of victories or failures. Which one will you give birth to?",
            " When we don't learn lessons at the right time, life will teach us the same lessons at the wrong time.",
            " We can smile even though we are hurting and we can feel happy even though we are unhappy. It's called strength.",
            " Don't worry when all you see is darkness. Behind the clouds there is always sunshine and blue skies.",
            " Disappointment is not the cause of your failure; it is because you left the belief of success.",
            " We generally love to sort out the truth from mysterious things, but do we sort out the truth of life, which is itself a mystery?",
            " You must take personal responsibility. You cannot change the circumstances, the seasons, or the wind, but you can change yourself.",
            " Losers live in the past. Winners learn from the past and enjoy working in the present toward the future.",
            " Music is the essence of the human soul. It expresses what cannot be expressed by other means.",
            " Smile will be complete when it begins with your heart, reflects in your eyes and ends with a glow on your face!!",
            " You don't ever have to take any of my advice, but if you're going to jump out of an airplane, I advise you grab a parachute.",
            " Don't think too much; don't wait for others to certify you. If you are right... go ahead and just do it.",
            " If you can't be star in the sky, at least be a lamp at home.",
            " Wisdom is the beautiful thing about age. When you have more behind you than in front of you, there is more to share.",
            " The FIGHT & DRIVE is not in OVERCOMING of a situation, it's the fact that you had the STRENGTH to OVERRIDE whatever it is in life that may have been trying to keep & hold you down.",
            " People often make two mistakes in their search of inner peace... focusing on things they cannot change, and ignoring things they can change.",
            " There is always SOMETHING behind NOTHING. That is why you could start from zero to zillions. Keep On Keeping On(KOKO)!",
            " If you're still looking for that one person who can change your life, take a look in the mirror.",
            " Happy people have two things in common. They know exactly what they want and they feel they're moving toward getting it. That's what makes life feel good: when it has direction, when you are heading straight for what you love.",
            " Just because you have problems, it doesn't mean you should not have Dreams. Instead, let your dream become the scheme to solve your problems.",
            " If you stand for a reason, be prepared to stand like a tree. If you fall onto the ground, fall like seed that grows back to fight again.",
            " Dreaming a dream is the process of molding a reality. Never stop dreaming, as yesterday's dream can become the reality of tomorrow and the innovation of the future.",
            " How can I not think about the past when it is because of it, that I am who I am today?",
            " Beauty might bring happiness, but happiness always brings beauty.",
            " Today is a wonderful and amazing day bursting with opportunity. Such is every day that is blessed by the light of day. Treat is as such, and you will see that the opportunities are innumerable and possibilities infinite.",
            " The further you spread your wings, the further you will fly.",
            " Each of us has a gift to share... none are insignificant... the gift of laughter, the gift of strength, the gift of love... let the light of your gift shine for all to see and feel... you never know who might need it.",
            " I'm like a Goalkeeper; I relax, I'm patient and enjoy myself but when the ball comes, I pay attention!",
            " Every Interaction is an Opportunity.",
            " No matter how qualified or deserving we are, we will never reach a better life until we can imagine it for ourselves and allow ourselves to have it.",
            " There is no use of running fast when you are on the wrong road.",
            " Avoid the crowd. Do your own thinking independently. Be the chess player, not the chess piece.",
            " Children are like flowers; let them bloom by giving them your warm smiles, your soft gentle words falling on them like rain and your air of confidence. You will be amazed at your own garden.",
            " Dare yourself, face your troubles and kill your fears.",
            " I align myself with people who support my growth. If you meet someone whose soul is not aligned with yours, send them love and move along.",
            "If you want to shrink something, You must first allow it to expand.If you want to get rid of something, You must first allow it to flourish. If you want to take something, You must first allow to be given. This is called the subtle perception of the way things are.",
            "Life is filled with gifts. They may not be the kind of gifts that we always want to have, often deemed by most of us as materials, but life gives us the best kind of gifts that no riches can ever provide. Just look around, feel within your heart and you will catch sight of them.",
            " To see yourself, do not look to the mirror; look to the eyes of the people.",
            " For you to learn, you have to listen; and for you to listen, you have to be silent. Did you know that listen and silent are words formed from the same letters?",
            " Life is simply continual ever-changing events... we control life changes or they control us. The choice is ours to make.",
            " Life laughs at you when you are unhappy. Life smiles at you when you are happy. But, Life salutes you when you make others happy.",
            " When you make a good decision, you want to own it because it helps your self-esteem. When you make mistakes, I want you to own those too, because that's how you learn. If you can't own bad choices, you can't own the good.",
            " It's very easy to find hundreds of excuses and very difficult to find one genuine reason, as to why I should do this??? And if found, don't forget the reason, as it will help you to achieve your goals when you are down or distracted.",
            " The secret of your happiness and your peace of mind is in your own hands. You, yourself are holding this key to your problems. So open the doors and let the light come in.",
            " Opportunity is always knocking. The problem is that most people have the self-doubt station in their head turned up way too loud to hear it.",
            " Your mind is the most powerful thing you possess, use it wisely or it will use you.",
            " Expecting and Accepting are the two sides of life: Expecting can end in tears, but Accepting will bring you cheers!",
            " We may have all come on different ships, but we're in the same boat now.",
            " Those who don't plan for their future are not interested in their future!",
            " Never change who you are. Never change how you learn. Change how you think!! Things are changing. I am willing to listen, learn, and change how I think!",
            "While losers compares their achievements with the failures of other people",
            "Winners always compares their achievements with their own goals, While losers compares their achievements with the failures of other people",
            "Best religjion �JAIN Best festival �PARYUSHAN� Best mantra �NAVKAR� Best granth �AAGAM� Best sutra �KALPSUTRA�",
            "If U want to enjoy, Alwys think today is the 1st day. But If U wnt to achieve sumthing, Alwys think today is the last day..",
            "You Cannot Change Your future But. U can change ur habits & sure ur habits will change ur future!",
            "A Winner never quit, But a quiter never win So choose the best one.",
            "Difficulties in your life don't come to destroy Y'R but to help u realise Y'R hidden potential & POWER",
            "Dream-More, Think-High, Choose-Best, Analyse-Twice, Plan-Perfect, Be-Confident, Work-Hard, Execute-Well, & Success will be all Urs..",
            "Wining Horse dsnt know why it runs in race, it runs bcoz of beats & pains. Life is a race: God is ur rider. So if u r in pain then think, God wants U to win.",
            "There is no Wine if Grapes r not pressed. No Perfume if Flowers r not Crushed. If u feel any Pressure in Life, It means God is bringing the best out of u.",
            "Victory is not the property of brilliant. It is the crown for those who bow themselves in front of hard work, Sincerity & Confidence.",
            "I have realised that even a solid thing like Iron becomes weak, when its hot and people use it as they wish. So just stay Cool..............",
            "Friends, Health and Time: These things don't come with price tag: But when we loose them, we realize the cost.",
            "Better to die on one's feet den to live on one's knees...",
            "People r lonely bcoz they build walls instead of bridge....",
            "Our necessities r few but our wants r endless.",
            "Men r born with 2eyes but 1tongue inorder dat they shud see twice as much as they say.",
            "Never leave on tommorrow which u can do today.",
            ".People generally quarrel bcoz they cannot argue.",
            "It is wise to direct our anger towards problems-not people, To focus our energies on answers-not excuses.",
            "Do good to everyone without expecting much As an old proverb says- Fragrances always cling to the hands Those who distribute roses",
            "If the Path is beautiful, ask where it leads to.. But if the Destination is beautiful, never mind about the path.. KEEP WALKING!!",
            "IF YOU WANT TO GO FAST, GO ALONE. IF YOU WANT TO GO FAR, GO TOGETHER",
            "YOU DON'T NEED BIGGER BOOBS. YOU NEED TO READ BETTER BOOKS.",
            "STUDY THE CLASSICS. WRITE YOUR OWN RULES",
            "Journey of life is exciting when you Challenge your own weaknesses. Sometimes your enemy Teaches you better than your friend.",
            "When you stop chasing the wrong things you give the right things a chance to catch you.",
            "Take Risks in Your Life If you Win, You Can Lead! If you Lose, You Can Guide!",
            "We Cannot Direct The Wind� But We Can Adjust The Sails",
            "Life Become Useless And Insipid When We No Longer Have Either Friends Or Enemies",
            "Life Is Not A Problem To Be Solved, But A Reality To Be Experienced",
            "Success is never achieved by the size of the brain. It is always achieved by the size of your thoughts. Always have a positive thoughts.",
            "Nothing in Life can keep us down except our own thinking, If we want a good quality of life then we must have a good quality of thoughts..",
            "Your mind is a garden,your thoughts are the seeds ,you can grow flowers or you can grow weeds,make your decision wisely.",
            " Be a better person today; always compete with yourself.",
            " Everything we do today is a seed sown in the garden of our life.",
            " The past is to prove that no one is perfect and the future is to prove that everyone can change.",
            " You have to make time for the things that you want. If you're not willing to sacrifice and make the time, you don't really want it.",
            " You are the result of your past choices. You will be the result of your future choices.",
            " Work hard because it takes time to be great, but the courage to fail is very cheap.",
            " When you focus on problems, you will have more problems and when you focus on possibilities, you will have more opportunities.",
            " A new day is the biggest opportunity of your life.",
            " I lost the battle when I made a mistake, but I won it back the moment I realized it.",
            " Life is like music, so it can be played in different styles.",
            " If you want light to come into your life you need to stand where it is shining.",
            " Simply ... winners meet the challenge rather than avoid it.",
            " Its better to be an example setter than to be an example teller.",
            " Are you bored with life? Then throw yourself into some work you believe in with all your heart, live for it, die for it, and you will find happiness that you had thought could never be yours.",
            "Someone who really Loves you sees what a mess you can be, how moody you can get, how hard you are to handle, but still wants you in their Life.",
            "Your life is a result of the choices you make... If you don't like your life it is time to start making better choices.",
            "Never get too attached to anyont because attachments leads to expectations and expectations leads to disappointments.",
            "Note to Self. I am doing the best I can with what i have in this moment And that is all I can except of anyone, including me!",
            "positive thinking sees the invisible, feels the intangible, and can achieve the impossible.",
            "Remember, anyont can love you when the sun is shining. In the storms is where you learn wh truly cares for you.",
            "TODAY will never come again. Be a blessing. Be a friend. ENCOURAGE someone. Take time to care. Let your words heal, and not wound",
            "Nothing binds you except your thoughts; nothing limits you except your fear; and nothing controls you except your beliefs",
            "YOU CAN EASILY JUDGE THE CHARACTER OF A MAN BY HOW HE TREATS THOSE WHO CAN DO NOTHING FOR HIM.",
            "Those who bring Sunshine into the lives of others cannot keep it from themselves.",
            "You need a plan to build a house. To build a life, it is even more iportant To have a plan or goal.",
            "WE MAKE A LIVING BY WHAT WE GET, BUT WE MAKE A LIFE BY WHAT WE GIVE",
            "INTELLIGENT WITHOUT AMBITION IS A BIRD WITHOUT WINGS.",
            "RUNNING AWAY FROM YOUR PROBLEMS IS A RACE YOU'LL NEVER WIN",
            "WALK LIKE YOU HAVE THERE MEN WALKING BEHIND YOU",
            "My father used to say, 'Don't Raise your voice. Improve your argument'",
            "THE HAPPINESS OF YOUR LIFE DEPENDS UPON THE QUALITY OF YOUR THOUGHTS",
            "Sometimes the questiONs are COMpliated aNd the aNswerS are SimpLe.",
            "DOING WHAT YOU LIKE IS FREEDOM LIKING WHAT YOU DO IS HAPPINESS",
            "Stars Can't Shine Without Darkness",
            "Fashion can be bought. style one must possess.",
            "Rock bottom became the solid foundatin on which I rebuilt my life.",
            "DO GOOD BECAUSE OF TOMORROW",
            "NEVER LOSE YOUR SENSE OF WONDER",
            "LIFE BEGINS AT THE END OF YOUR COMFORT ZONE.",
            "Things do not happen, They are made to happen!",
            "It doesn�t matter where you start. Only that you begin. Unless you begin, you will never complete. So, just start, have the confidence and you shall succeed in your task. Have a successful day, today!",
            "Life offers you a lot of invitations� Be wise enough to choose which are worth attending to.",
            "Strong people do not put others down� They lift them up",
            "You can�t reach for anything new if your hands are still full of yesterday�s junk.",
            "Don�t let your wounds to turn you into a person you are not!",
            "MY BIGGEST influence are S T R O N G, C R E A T I V E  W O M E N that chart their own path, lead their own lives & drive the course of history",
            "PLAYING DRESS-UP BEGINS AT AGE FIVE AND NEVER TRULY ENDS.",
            "SHE STOOD IN THE STORM & WHEN THE WIND DID NOT BLOW HER AWAy. SHE ADJUSTED HeR SAILS.",
            "THER IS A CERTAIN HAPPIESS IN BEING SILLY AND RIDICULOUS",
            "I CAN'T DO THIS BUT I'M DOING IT ANYWAY",
            "You exist... but do you live?",
            "you know all tHose tHiNGs you've always Wanted to do? you should go DO THEM.",
            "The difference between genius and stupidity is that genius has its limits",
            "LET THE REFINING AND IMPROVING OF YOUR OWN LIFE KEEP YOU SO BUSY THAT YOU HAVE LITTLE TIME TO CRITICIZE OTHERS.",
            "THERE IS NO DIET THAT WILL DO WHAT EATING HEALTHY DOES.",
            "Someone else is happy with less than what you have.",
            "IT'S NOT HARD TO MAKE DECISIONS ONCE YOU KNOW WHAT YOUR VALUES ARE.",
            "WORRYING WILL never CHANGE THE outcome.",
            "The only disability in life is a bad attitude.",
            "BE SO HAPPY that WHEN OTHERS look at you THEY BECOME HAPPT too.",
            "If you are not willing to look stupid, nothing great is ever going to happen to you.",
            "Accept what You Can't Change, Change What You Can't Accept.",
            "Sometimes I have to REMIND myself that I don't have to do what EVERYONE ELSE is doing.",
            "LOVE IS NOT JUST LOOKING AT EACH PTHER, ITS LOOKING IN THE SAME DIRECTION.",
            "It is right to say that 'GOOD THINGS COME TO THOSE WHO WORK THEIR ASSES OFF AND NEVER GIVE UP' instead of 'GOOD THINGS COME TO THOSE WHO WAIT'.",
            "BE THE TYPE OF PERSON YOU WANT TO MEET",
            "IN ORDER TO LEAD A FASCINATING LIFE--ONE BRIMMING WITH ART,MUSIC, INTRIGUE AND ROMANCE--YOU MUST SURROUND YOURSELF WITH PRECISELY THOSE THINGS.",
            "COLLECT MOMENTS/NOT THINGS",
            "YOUR Beliefs DON'T MAKE YOU A BETTER PERSON, YOUR Behavior DOES",
            "SUFFER THE PAIN OF DISCIPLINE OR SUFFER THE PAIN OF REGRET",
            "Anyone can make you happy by doing something special. But, only someone special can make you happy WITHOUT DOING ANYTHING.",
            "SoMeTimeS The WRoNg CHoCES bRiNg uS To THe RigHT PLACES",
            "WORRYING DOES NOT EMPTY TOMORROW OF ITS TROUBLES IT EMPTIES TODAY OF ITS strength",
            "if you obey all the rules, you miss all the fun.",
            "Don't think too much. you'll create a problem that wasn't even there in the first place.",
            "IF YOU CAN'T GET RID OF THE SKELETON IN YOUR CLOSET YOU'D BEST TAKE IT OUT AND TEACH IT TO DANCE",
            "LET HER SLEEP FOR WHEN SHE WAKES SHE WILL MOVE MOUNTAINS",
            "WHAN LIFE GIVES YOU CURVES FLAUNT THEM",
            "THE CURE FOR ANYTHING IS salt water SWEAT, TEARS OR THE SEA",
            "Speak the truth, even iF your voice shakes",
            "IF YOU WANT YOUR CHILDREN TO BE INTELLIGENT, READ THEM FAIRY TALES.",
            "the most wasted of ALL DAYS is one without LAUGHTER.",
            "A dog is the only thing on earth that loves you more than he loves himself",
            "LIFE IS HARD;IT'S EVEN HARDER IF YOU'RE STUPID.",
            "I'd rather have flowers on my table than diamonds on my neck",
            "SoMeTimeS THE WRONg choices BRiNg uS To THe RigHT PLACeS.",
            "PUT A DEADLINE TO YOUR DREAMS, AND THEY BECOME GOALS.",
            "CUTTING LIBRARIES IN A RECESSION IS LIKE CUTTING HOSPITALS",
            "Don't compare your life to others. You have no idea what their journey is all about.",
            "NEVER CoNFuSE EDUCATION WiTH INTELLIGENCE",
            "KiND WORDS CAN BE SHORT & EASY TO SPEAK, BUT THEIR ECHOES ARE TRULY ENDLESS",
            "Hard words cannot touch any soft heart but soft words can touch any hard heart, so speak softly and win the world.",
            "Bw strong enough to allow yourself the freedom to stand apart from the crowd. But wise enough to stand with others when the time is right.",
            "Respect is earned. Honesty is appreciated. Trust is gained. Loyality is returned.",
            "FOLLOW YOUR HEART BUT TAKE YOUR BRAIN WITH YOU.",
            "if your problem in life is as big as a ship, Never forget that your blessings Are as wide as the ocean!",
            "Always pray to have eyes that see the best in people, a heart that forgives the worst, a mind that forgets the bad, and a soul that never loses faith in God.",
            "FAITH is like Wi-Fi, it's invisible but it has the power to connect you to what you need.",
            "Don't blame people for disappointing you. Blame yourself for expecting too much.",
            "Mistakes are painful when they happen. But year's later collection of mistakes is called experience, which leads to success.",
            "Believing everybody is dangerous; Believing nobody is very dangerous;",
            "If someone feels that they had never made a mistake in their life, then it means they had never tried a new thing in their life..",
            "Talk To Yourself Once In A Day... Otherwise You May Miss Meeting An Excellent Person in this World",
            "BEAUTY attreacts the eye but PERSONALITY captures the HEART.",
            "it's better to cry alone than to be angry BECAUSE anger hurts others,while tears flow silently through the soul and washes the heart.",
            "You are never too old to set another goal or to dream a new dream..",
            "You have to fight through some bad days to earn the best days of your life.",
            "THERE ARE TWO WAYS OF SPREADING LIGHT TO BE THE CANDLE OR THE MIRROR THAT REFLECTS IT",
            "dON'T CARRY YOUR MISTAKES AROUND WITH YOU. Instead, place them under your feet and use them as stepping stones. Never regret. If it's good, it's wonderful. If it's bad, it's experience.",
            "NEVER CRY for the peson who hurts you. Just smile & say thanks for giving me a chance to find someone better than you.",
            "Never Play With The Feelings Of Others Because You May Win The Game. But You Will Surely Lose The Person For Life Time.",
            "you don't step laughing because you grow old, you grow old because you stop laughing...",
            "Don't compare yourself with anyone inthis world. If you do so, you are insulting yourself.",
            "If a problem can be solved, no need to worry about it. If a problem cannot be solved what is the use of worrying?",
            "Never break four things in your life - Trust, Promise, Relation & Heart because when they break they don't make noise but pains a lot ?",
            "Friends are like the clouds in the sky, They hang around for you even when you don't want 'em to !",
            "Always pray to have eyes that see the best, a heart that forgives the worst, a mind that forgets the bad, & a soul that never loses faith.",
            "YOU CAN'T LIVE A positive life WITH A NEGATIVE MIND.",
            "There are two great days in a persons life. The day we are born and the day we discover Why.",
            "SMILE AND LET EVERYONE KNOW THAT TODAY YOU'RE A LOT STRONGER THAN YOU WERE YESTERDAY.",
            "Everyone thinks of changing the world, but no one thinks of changing himself...",
            "As long as we have memories, yesterday remains, as long as we have hope, tomorrow awaits, as long as we have friendship, each day is never a waste..",
            "Don't trust too much Don't love too much Don't hope too much  Because that too much Can hurt you so much",
            "Everything in the universe wants to be loved and accepted. Our personal work is to find the love and acceptance within ourselves.",
            "What is Success ? When your 'Signature' changes to 'Autograph'",
            "When you do things from your soul, You feel a river moving in you, a joy.",
            "Don�t let yourself be controlled by these three things:your past,people,and money�",
            "Tomorrow�s success depends on today�s effort!",
            "Three sentences for getting SUCCESS: know more than other work more than other expect less than other",
            "The greatest advantage of speaking the truth is that you don�t have to remember what you said.",
            "It is Very Easy To Defeat Someone,But It Is Very Hard To Win Someone",
            "Work without faith is like an attempt to reach the bottom of a bottomless pit.",
            "THE ONLY REASON FOR TIME is so that Everything DOESNT is HAPPEN atonce.",
            "Stop being AFRAID OF what COULD GO WRONG, AND focus ON WHAT Could GO RIGHT.",
            "At the end of the day people will remember what you did but not who you did it for so as much as possible do things because you want to and not because someone asks you to do it",
            "Life is too short to stress yourself with people who don�t even deserve to be an issue in your life.",
            "DUNIYA TUMHEIN US WAQT TAK NAHIN HARA SAKTI, JAB TAK KI TUM KHUD SE NA HAR JAO.",
            "Enjoy every moment you have. Because in life, there are no rewinds, only flashbacks. Make sure it�s all worth it!",
            "The way of peace is the way of truth. Truthfulness is even more important than peacefulness.",
            "The tongue has no bones, but is strong enough to break a heart. So be careful with your words.",
            "thought BECOME words WHICH BECOME YOUR actions WHICH BECOME YOUR habits WHICH BECOME YOUR character WHICH BECOMES YOUR destiny",
            "Action without words  are c o n f u s i n g .. and WORDS without actions are e m p t y.",
            "When You Lose Control Of Your Thoughts,You Lose Control of Your life.",
            "A man of faith will remain steadfast to truth even though the whole world might appear to be enveloped in falsehood.",
            "Do not let what you cannot do interfere with what you can do.",
            "WE CANNOT SOLVE OUR PROBLEMS WITH THE SAME THINKING WE USED WHEN WE CREATED THEM",
            "Don't cry over the past,it's gone.Don't stress about the future,it hasn't arrived. Live the present moment,make it beautiful.",
            "Be curious not judgmental.",
            "If you feel like doing some work, sit down and wait... The feeling does go away.",
            "Be happy for no reason, like a child. If you are happy for a reason, you're in trouble, because that reason can be taken from you.",
            "THE TRUE PURPOSE OF EDUCATION IS  TO MAKE MINDS, NOT CAREERS.",
            "Mystery creates wonder and wonder is the basis of man's desire to understand.",
            "Never stop doing little things for others. Sometimes,those little things occupy the biggest part of their heart.",
            "I told God protect me from my enemies and I started losing friends...",
            "Dreams is not what you see in sleep is the thing which doesn't let you sleep.",
            "You will not be punished FOR your anger; you will be punished BY Your anger.",
            "EVERY TIME YOU SUBTRACT NEGATIVE FROM YOUR LIFE, YOU MAKE ROOM FOR MORE POSITIVE.",
            "YOUR THOUGHTS DETERMINE YOUR EXPERIENCE LAW OF ATTRACTION",
            "'EGO' is the only requirement to destroy any relationship...so be the bigger person skip the 'E' and let it 'GO'",
            "family... where life begins and love never ends",
            "Your time is limited; don't waste it living someone else's life.",
            "I will not say I failed 1000 times , I will say that I discovered there are 1000 ways that can cause failure--",
            "Yesterday is done and gone. Today is the first day of my Future.",
            "Never hate people who are jealous of you, but respect their jealously because they're the ones who think that you're better than them.",
            "I CAN DO THINGS YOU CANNOT, YOU CAN DO THINGS I CANNOT; TOGETHER WE CAN DO GREAT THING.",
            "We cannot alter facts, but we can alter our ways of looking at them.",
            "Life is something like a trumpet. If you don't put anything in it, you don't get anything out. And that's the truth.",
            "The difference between school and life? In school, you're taught a lesson and then given a test. In life, you're given a test that teaches you a lesson.",
            "Far away in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty, believe in them, and try to follow where they lead.",
            "A paper flying in air is due to luck But, A bird flying in air is its Effort, So be a Bird and struggle with hurdles To become Successful............",
            "Life is a great big canvas; throw all the paint on it you can.",
            "There is no such thing as a 'self-made' man. We are made up of thousands of others. Everyone who has ever done a kind deed for us, or spoken one word of encouragement to us, has entered into the make-up of our character and of our thoughts, as well as our success.",
            "To be wronged is nothing unless u continue to remember it.",
            "A life spent in making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
            "If a problem has no solution, it may not be a problem, but a fact - not to be solved,but to be coped with over time.",
            "The shortest way to do many things is to do only one thing at a time.",
            "The highest achievement of mankind is not the skyscrapers or mightl machines or the atom bomb. It is the ability to break the barriers of selfishness, to cross the limits of ignorance, and to love other human being without condition.",
            "Unlike fairy tales, life has tears and failures. And, that is why life is more beautiful than fairy tales!",
            "Respect those who care regardless of their monetary status. Remember, a caring zero is still better than a distant hero!",
            "When I drink water, I remember the people who died of thirst. When I eat, I remember the desperation reflected in the eyes of the hungry. When I am grateful, all simple things of life turn into blessings!",
            "Celebrate today. A postponed joy loses its emptions and relevance.",
            "Hope is a great vehicle, and it's fuel is hard-work.",
            "It is easy to forgive others, difficult to forgive self!",
            "It is always easy to laugh at others;sharing a smile requires lot more work.",
            "Its Not hard to 'Sacrifice' something for someone But Its hard to Find that Someone who DESERVES Your 'Sacrifice'...!!!",
            "7 secrets of Success... I found the answers in my room. Roof said: Aim high Fan said: Be cool Clock said: Every min. is precious Mirror said: Refect before you act Window said: See the world Calender said: Be up-to-date Door said: Push hard to achieve ur goals.",
            "Always End the Day With a Positive Thought. No Matter How Hard Things Were, Tomorrow's a Fresh Opportunity to Make it Better.",
            "FAILURES DO WHAT IS TENSION RELIEVING, WHILE WINNERS DO WHAT IS GOAL ACHIEVING.",
            "DON'T FORGET TO BE AWESOME..",
            "If we don't learn to control our thoughts, we will never learn to control our behavior",
            "It's not an issue of Wants vs. Needs. It's an issue of Wants vs. Priorities.",
            "DON'T TAKE THINGS personally. What other people say about you is their reality, not yours.",
            "Every STORY has an END But'in LIFE every end is a NEW BEGINNING",
            "I CHOOSE to make The REST of my life The BEST of my life.",
            "You wereborn to make mistakes, not to fake perfection.",
            "Learn the facts Before assuming Understand why Before judging Think Before speaking Feel Before hurting!",
            "Patience is not the ability to wait, but the ability to keep a good attitude while waiting.",
            "You can't win until you're not afraid to lose",
            "Success is when you teach someone else to do something better than you.",
            "I think it's very healthy to spend time alone. You need to be alone and not be defined by another person.",
            "When you thought I wasn't looking, I saw tears come from your eyes, And I lerned that sometimes things hurt, But it's all right to cry.",
            "The beauty of life does not depend on how happy you are, but on how happy others can be because of you.",
            "When we commit to ourselves that we will remain happy under all conditions then we find happiness in all walls of life.",
            "Everyone has beauty but not everyone sees it.",
            "NOBODY CAN GIVE YOU FREEDOM NOBODY CAN GIVE YOU EQUALITY OR JUSTICE IF YOU A MAN YOU TAKE IT",
            "Never tell your problems to anyone. 20% don't care and the other 80% are glad you have them.",
            "TODAY WILL NEVER COME AGAIN Be a blessing Be a friend Encourage someone Take Time To Care. Let your words heal, and not wound.",
            "O Allah, if I hurt others, give me the strength to apologize. If people hurt me, give me the strength to forgive.",
            "If You Born Poor, it's Not Your Mistake But If You Dies Poor, it's Definitly Your Mistake.",
            "SILENT PEOPLE HAVE THE LOUDEST MINDS"};

    public static String get_currentMonth(int pos) {
        return arr_month[pos];
    }

    public static String get_todayThought(int pos) {
        return arr_thought[pos];
    }
    public static String savePath = Environment.getExternalStorageDirectory().getPath();

    public static void shareCard(Context context, View view) {
        try {

            view.setDrawingCacheEnabled(true);
            Bitmap bitmap = view.getDrawingCache();
            File file = new File(savePath, "today_thought.jpg");
            FileOutputStream fOut = new FileOutputStream(file);
            bitmap.compress(Bitmap.CompressFormat.PNG, 60, fOut);
            fOut.flush();
            fOut.close();
            file.setReadable(true, false);


            Uri sharedFileUri = FileProvider.getUriForFile(context,"com.gpfreetech.card.fileprovider", file);
            ShareCompat.IntentBuilder intentBuilder = ShareCompat.IntentBuilder.from((Activity) context).setType("image/jpg").addStream(sharedFileUri);
            Intent chooserIntent = intentBuilder.createChooserIntent();
            context.startActivity(chooserIntent);
/*
            final Intent intent = new Intent(android.content.Intent.ACTION_SEND);
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            intent.putExtra(Intent.EXTRA_STREAM, Uri.fromFile(file));
            intent.setType("image/jpg");
            context.startActivity(Intent.createChooser(intent, "Share image via"));*/
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
